### ISSUE TITLE
Image is too large

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/coss#328]
There are a few images that are too big and are affecting the load time
eg https://coss-staging.mozilla.community/static/img/alex-wong.jpg?2fc24fe23974

**Comment by m-branson** [comment]
Yep, this image isn't in use anymore. Was just placeholder, see #313 for the latest.

This does bring up image compression overall though. In order to get hi-resolution images on the site, we need content admins to be able to upload large images. Ideally the CMS would compress and call the 'correct' size image based on where it's being loaded e.g. mobile vs. desktop; retina vs non-retina. We should avoid uploading images that are small and lo-resolution to accomplish fast load times. There is a way to do this, I'm just not technically familiar with the specifics.

**Comment by m-branson** [comment]
@akatsoulas also reference #95 -- my comment there re: image transforms and focal points is something we should start thinking about sooner than later.

cc @a-kilroy

**Comment by akatsoulas** [comment]
Relevant to this discussion:
http://docs.wagtail.io/en/v1.12.1/editor_manual/documents_images_snippets/images.html
http://docs.wagtail.io/en/v1.12.1/advanced_topics/images/feature_detection.html

The image manipulation can be done through the CMS admin interface.
