### ISSUE TITLE
Determine GitHub labels

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#33]
I know @a-kilroy wants to be very intentional about the labels we use/create so that they can be used across multiple repos.

Here's what this repo has so far:
- bug
- business engineering
- cms
- duplicate
- Epic
- salesforce
- Sprint Goal
- UI
- UX
- visual design 

Here are a few other ideas:
- Clubs
- QA
- front-end
- back-end
- API (?)
- help wanted (for contributors)
- enhancement 
- blocked
- we have also used P1 and P2 to identify priorities within a sprint

cc @hannahkane since you probably have some thoughts?

**Comment by hannahkane** [comment]
I think labels can be very project-specific, so I won't have a very strong opinion here, since I haven't been super involved. In my experience, labels are most useful for a) helping contributors find issues to work on (as in "help wanted" or "good first bug"), and b) helping to filter work by functional area (e.g. design, engineering). For the latter, I'd suggest only going as granular as the team structure calls for (that is, if there is someone responsible for UI and another person responsible for UX, then labels for each makes sense. If the work is going to be done by the same person, maybe just "design" would be sufficient.)

If the repo is going to hold multiple projects, you could use labels for that (e.g. "Clubs"), though github's Projects feature works pretty well for that.

I personally try to avoid process labels as much as possible. I believe you guys are using zenhub, which makes "P1," "P2," "QA," and "Blocked" unnecessary, because you can just use zenhub boards to track statuses (i.e. have a column for "blocked" or "In QA") and priority (order issues by importance).

It's difficult to use labels consistently, so I'd err on the side of having as few as possible. 

Just my two cents!

**Comment by kristinashu** [comment]
Excellent insight, thanks Hannah!

**Comment by a-kilroy** [comment]
Really helpful, thanks!
