### ISSUE TITLE
Add placeholder photo if no photo is added by the content owner for an entity

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/coss#379]
On [Category landing page](https://coss-staging.mozilla.community/category-landing-page/), the content owner has the option to add no photo for an entity, and that entity card is of different size. 
![photos.png](https://images.zenhubusercontent.com/589c8bd951aa2c305773eb64/ce4438c2-0d53-4b68-8578-1dc3054f7edd)
Should we add a placeholder photo, for the case where the content owner choose not to add a photo, for consistency? 
CC: @m-branson

**Comment by m-branson** [comment]
A couple of thoughts on this:

1. The images used on the Entity Cards should be dynamically pulled from the primary (header) image used on the Entity Page. These images will be of a campus, city landscape, etc. The images will be wide shots and not utilize faces or people. 
2. For the build, if no primary image is uploaded for the Entity, is it possible to default to a map image based on entity location? This map would appear both at the top of the Entity Page and display on the Entity Card. This will help the entities still appear unique, despite not having a primary image. I attempted to convey this in our early concept prototype [here](https://projects.invisionapp.com/share/UYC9ST17F#/screens/240171465). On that Entity Page the map header image is default and based on location (San Francisco) because no primary image has been uploaded by the admin. 
3. For the staging site can we use placeholder images that aren't of people's faces so we don't cause additional confusion? Ideally pull images from [Unsplash](https://unsplash.com/about), they have an [API](https://unsplash.com/developers). This will better help content admins understand what kind of photo should go where. 👍 

cc @a-kilroy

**Comment by a-kilroy** [comment]
So I think some of these solutions could be fine for long term but are clearly too much scope creep for launch. To be clear @viorelaioia and @m-branson we should have images for all of the Entities we will launch with and if not, we need to follow up with @LucyeoH and @bacharakis (can check later too myself)
