### ISSUE TITLE
Establish Front Facing Web Property

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#40]
This is the Epic for our website. Some example tickets associated with this but we should all jump in to edit them and add to them. In my mind the there are two paths, production and 'design/testing' so steps in a non waterfall timeline are: Install, wireframe, test wireframes, light visual design, content upload, refine design, integrations

**Comment by Pomax** [comment]
In order to prioritise projects with deadlines, some focus is shifting from "mezzanine as applicable to CoSS" (specifically, clubs) to "mezzanine as applicable to the Network site that's being built". with the booknote that this is a bias adjustment, not a full course change, so work will still happen for coss, it just takes a backseat to Network in the priority list.
