### ISSUE TITLE
Different size in collaborator boxes

### ISSUE THREAD

**Issue by bacharakis** [mozilla/coss#458]
In the collaborators section under the About page the size of the different collaborator boxes is inconsistent.

**Comment by a-kilroy** [comment]
@bacharakis Screenshots with specific comments would have been really helpful here. After looking I am guessing you mean the Github and the GNOME project ones. I suspect the Github is sized weird because of the image you chose (already a circle) but we are looking into it. Not sure about the GNOME project, will investigate. Was there something else you saw? Please add screenshots with comments in the previously outlined format.

**Comment by bacharakis** [comment]
Yes I am talking about the Gnome project one. I thought this was a known issue since I have brought it to the devs' attention some time ago.

In any case I don't think the issue here is the size of the image but the length of the title "Gnome Project".

**Comment by viorelaioia** [comment]
This is not fixed entirely. 
We should restrict the size of a link text displayed on a card (see example for Open Campus). 
For a few cards (See Red Hat or Open Campus), the 3rd row of text is not shown anymore.
![About.png](https://images.zenhubusercontent.com/589c8bd951aa2c305773eb64/4953c7e8-559d-4db6-9e8a-f540985f533b)

**Comment by comzeradd** [comment]
There was an empty paragraph on top of these texts. I clean them up and look fine now.

Good catch for the cta link. I'll open a PR for this.
