### ISSUE TITLE
Wireframes for Clubs about page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#51]
Based on wireframes in #38 https://invis.io/72AN1X8WT#/221087690_Home

I will take a closer look at this page and iterate on it.

Will also need copy #49 and possibly images #50.

![about 2x](https://cloud.githubusercontent.com/assets/1068783/23723218/2f752c04-03fd-11e7-96de-aed4e261e6a0.jpg)

**Comment by kristinashu** [comment]
Updated this so we now have an Overview About page (which would cover basic info about Clubs like the different roles) and then separate sub-pages for each individual club type (which would cover individual club's mission, vision...).

Copy is completely placeholder but please let me know what you think of the general structure @LucyeoH @bacharakis @jvallera @amirad

All wireframes are in [InVision](https://invis.io/72AN1X8WT#/221087702_About)

![about 2x](https://cloud.githubusercontent.com/assets/1068783/24480931/21aed4bc-149c-11e7-9dd7-92d8bab2caf0.jpg)
![about campus 2x](https://cloud.githubusercontent.com/assets/1068783/24480930/21ae8afc-149c-11e7-970c-a27afb5c1c16.jpg)

**Comment by amirad** [comment]
Thanks @kristinashu this looks great. As per the layout I think this works well. I'm not sure if Open Source, Web Lit and WWL are the right titles on the side. Maybe we switch those out with the Internet health themes and talk about how clubs address each theme? We will need to make open source the majority of open innovation.

**Comment by bacharakis** [comment]
Thank you so much @kristinashu, they are great! :D

We are only checking the structure right? Because in terms of content (and this is still an on-going conversation) I would suggest to use "Register a Club" instead of Become a Club Captain as we have been discussing. 

In terms of structure (and this this is an on-going conversation) and looking forward, when we maybe have more types/categories of Clubs, I wonder how can we highlight each topic's similarities but also differences. For example what's the difference between the Web Literacy and the Women & Web Literacy, or with Open Source?

**Comment by a-kilroy** [comment]
@bacharakis  for your structure comment, I think we can deal with that when it becomes an issue. We should have a lot more functionality by then so the solutions might be different

**Comment by kristinashu** [comment]
Excellent, sounds like the functionality is there so I'm going to close this ticket!
